branches:
  only:
  - master
  - release
language: python
python:
- '3.4'
before_script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    pip install pygithub;
    pip install pygithub3;
  fi
script:
- python3 tools/sqf_validator.py
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    python3 tools/deploy.py;
  fi
env:
  global:
  - secure: gNP9Jq0LAonkao58GHXPsCGwIUD9sobwH/QP/n0LLA17g7X5Oui5iqlR7HvH/fEv67gLQUAnRTbvU8Sx+7EwTo89aQjp2lVuvY2Dom3D1oLcmwKuOj4rShgaNBwjb6ccc434IKKibssL9HVPIKwafaGIWknGoCUaZ9Ue6NfG7kQ1ag+/8hsWSxYx4M7AIFiby2HfeMR2wnkBCNMyIa8zp7zVBkz0bm4kGDvb9pth8N/wR/kJrE7WQnJNYl73iHJQaRFGxklMzOqk/17rGcxVP+DoIEh6EY6syfVRMP9kG1ACmmfBTuqakbz7MgmrirsRDseSpN8D2k3ORtPTQ1NLwifbpn5pg3KjumF+Jj+vVBc2RxU6CN4+Ustd/VWiqwa9IKgfbgLdMh+MXZP2Jeqcd3IJI4gz5/ArpszrlYPbjzJvS+XaqdTXeqlBGE9IMvPssQoW+GKUXXUGKtNOQHN1LY8P2+z+ABTBPRiBJQ9xbuGWaUhKndTk0w7lZh9DaLGRlKS66hyiVYXlGcZJCXNw+CVS2j3iQdGDuM6xvtcwOaSV6/WnYPWSF6J4fZiz9OZiYO3U5adrqsFKE43GiYMrIeIvHAc6ghy1VwZP0IvNsyYqwx86i8Vm9kANECjIubB/iuzWsY2AkrEqGgz059LqAKG1T3QJ7IU49O+lYESUzFs=
notifications:
  email:
    on_success: never
    on_failure: change
